apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-sql
data:
  init.sql: |
    CREATE DATABASE hive;
    CREATE USER hive WITH LOGIN SUPERUSER PASSWORD 'password';
    GRANT ALL PRIVILEGES ON DATABASE hive TO hive;
    CREATE DATABASE metastore_db;
    GRANT ALL PRIVILEGES ON DATABASE metastore_db TO hive;
    CREATE DATABASE hue;
    CREATE USER hue WITH LOGIN SUPERUSER PASSWORD 'password';
    GRANT ALL PRIVILEGES ON DATABASE hue TO hue;
