apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-server
  template:
    metadata:
      labels:
        app: hive-server
    spec:
      initContainers:
      - name: hadoop-init
        image: apache/hadoop
        securityContext:
          runAsUser: 0
        envFrom:
        - configMapRef:
            name: hadoop-config
        args:
          - cp 
          - -a
          - /opt/hadoop/etc/hadoop/.
          - /hadoop-conf
        volumeMounts:
        - name: opt-hadoop
          mountPath: /hadoop-conf
      - name: hbase-init
        image: sebssekk/hbase
        command:
        - /bin/bash
        - -c
        args:
        - |
            cp /opt/hbase/lib/hbase*.jar /hbase-jar
            cp /opt/hbase/lib/opentelemetry*.jar /hbase-jar
            cp /opt/hbase/lib/zoo*.jar /hbase-jar
            
        volumeMounts:
        - name: hbase-jar
          mountPath: /hbase-jar
      containers:
      - name: hive-server
        image: apache/hive
        command: 
        - /bin/sh
        - -c
        args: 
        - |
           cp /hbase-jar/* /opt/hive/lib/
           /entrypoint.sh
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.2"
          limits:
            memory: "2.5Gi"
            cpu: "1"
        ports:
        - containerPort: 10000
          name: thrift
        - containerPort: 10002
          name: http
        env:
        - name: SERVICE_NAME
          value: hiveserver2
        - name: SERVICE_OPTS
          value: "-Dhive.metastore.uris=thrift://hive-metastore:9083"
        - name: IS_RESUME
          value: "true"
        volumeMounts:
        - name: opt-hadoop
          mountPath: /opt/hadoop/etc/hadoop
        - name: site-config
          mountPath: /opt/hive/conf/hive-site.xml
          subPath: hive-site.xml
        - name: hbase-jar
          mountPath: /hbase-jar
      volumes:
      - name: opt-hadoop
        emptyDir: {}
      - name: hbase-jar
        emptyDir: {}
      - name: site-config
        configMap:
          name: hive-conf
