apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include per-product kustomizations
resources:
  - hadoop
  - hive
  - spark
  - hue
  - hbase
  - kafka

# Add a label used to target the pod-spec patch for all resources
labels:
  - pairs:
      stack: bigdata

# Control container images centrally from this file (edit newName/newTag as needed)
images:
  - name: apache/hadoop
    newName: sebssekk/hadoop
    newTag: 3.4.2-jdk21
  - name: postgres
    newTag: "latest"
  - name: apache/hive
    newTag: "4.2.0"
  - name: apache/spark
    newTag: "4.1.0-java21-python3"
  - name: gethue/hue
    newTag: "4.11.0"
  - name: zookeeper
    newTag: "latest"
  - name: sebssekk/hbase
    newTag: "2.6.4"
  - name: apache/kafka
    newTag: "4.1.1"

# Apply a single patch file to both Deployments and StatefulSets that have label stack=bigdata
patches:
  - path: common/podspec-patch.yaml
    target:
      kind: Deployment
  - path: common/podspec-patch.yaml
    target:
      kind: StatefulSet
